name: crmapp

services:
  api:
    build: ./backend
    container_name: crm_api
    volumes:
      - ./backend:/var/www/backend:cached
      - laravel_storage:/var/www/backend/storage
      - laravel_cache:/var/www/backend/bootstrap/cache
    restart: always
    environment:
      MYSQL_HOST: db
      # Database Configuration
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      
      # Laravel Configuration
      APP_NAME: ${APP_NAME:-Laravel}
      APP_ENV: ${APP_ENV:-local}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_URL: ${APP_URL:-http://localhost:8080}
      APP_LOCALE: ${APP_LOCALE:-en}
      APP_FALLBACK_LOCALE: ${APP_FALLBACK_LOCALE:-en}
      
      LOG_CHANNEL: ${LOG_CHANNEL:-stack}
      LOG_STACK: ${LOG_STACK:-single}
      LOG_DEPRECATIONS_CHANNEL: ${LOG_DEPRECATIONS_CHANNEL}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST:-searcher}
      ELASTICSEARCH_PORT: ${ELASTICSEARCH_PORT:-9200}
    networks:
      - angular-laravel
      - laravel-mysql
      - elastic
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 9000

  load_balancer:
    build: ./nginx
    container_name: crm_load_balancer
    volumes:
      - ./backend/public:/var/www/backend/public
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - angular-laravel

  db:
    image: mysql:9.3.0
    container_name: crm_db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    ports:
      - 127.0.0.1:3307:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel-mysql

  searcher:
    image: elasticsearch:9.0.1
    container_name: crm_searcher
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - elastic
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  db-data: {}
  laravel_storage: {}
  laravel_cache: {}
  elasticsearch_data: {}

networks:
  angular-laravel: {}
  laravel-mysql: {}
  elastic:
    driver: bridge

