name: crmapp-v2.0.1

services:
  api:
    build: ./backend
    volumes:
      - laravel_storage:/var/www/backend/storage
      - laravel_cache:/var/www/backend/bootstrap/cache
    restart: always
    env_file:
      - laravel.env
    networks:
      - angular-laravel
      - laravel-mysql
      - elastic
    depends_on:
      db:
        condition: service_healthy

  load_balancer:
    build: ./nginx
    volumes:
      - ./backend/public:/var/www/backend/public
    ports:
      - "8082:80"
    depends_on:
      - api
    networks:
      - angular-laravel

  db:
    image: mysql:9.3.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    ports:
      - 127.0.0.1:3309:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel-mysql

  searcher:
    image: elasticsearch:9.0.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9202:9200"
      - "9302:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - elastic
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  db-data: {}
  laravel_storage: {}
  laravel_cache: {}
  elasticsearch_data: {}

networks:
  angular-laravel: {}
  laravel-mysql: {}
  elastic:
    driver: bridge

